version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - cargo build

  test:
    desc: Run tests
    cmds:
      - cargo test

  lint:
    desc: Run clippy for linting
    cmds:
      - cargo clippy -- -D warnings

  format:
    desc: Format the code
    cmds:
      - cargo fmt -- --check

  check:
    desc: Run all checks (format, lint, test)
    cmds:
      - task: format
      - task: lint
      - task: test

  run:
    desc: Run the application (Stdio)
    cmds:
      - cargo run

  run:http:
    desc: Run the application (HTTP)
    cmds:
      - cargo run -- http

  build:amd64:
    desc: Build for AMD64
    cmds:
      - cross build --target x86_64-unknown-linux-musl --release

  build:arm64:
    desc: Build for ARM64
    cmds:
      - cross build --target aarch64-unknown-linux-musl --release

  coverage:
    desc: Run coverage report
    cmds:
      - cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
